config/routes.rb
TourApp::Application.routes.draw do
  resources :agents

  mount StripeEvent::Engine => '/stripe'
  devise_for :users, :controllers => { :registrations => 'users/registrations' }
  devise_scope :user do
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users, :except => [:edit, :show]

  # devise_for :users
  # resources :users
  resources :tours, :except => [:index] do
    resources :photos, only: [:new, :create, :destroy] 
  end

  match '/tours/:id/delete_photos', to: 'tours#delete_photos', via: 'get'

  resources :photos do
    collection { post :sort }  # from railscasts #147... not sure if I need this
  end

  resources :leads, only: [:create, :index]

  resources :charges

  root :to => 'static_pages#home' 

  # Sales Pages
  match '/home',      to: 'static_pages#home' ,     via: 'get'
  match '/features',  to: 'static_pages#features',  via: 'get'
  match '/about',     to: 'static_pages#about',     via: 'get'
  match '/contact',   to: 'static_pages#contact',     via: 'get'
  match '/survey',    to: 'static_pages#survey',    via: 'get'
  match '/signup',    to: 'users#new',              via: 'get'
  match '/sample1',   to: 'tours#sample_tour1',     via: 'get'
  match '/sample2',   to: 'tours#sample_tour2',     via: 'get'

  # Blog
  namespace :blog do
    resources :articles, path: '', only: [:index, :show]
  end

  # App
  match '/signin',    to: 'sessions#new',         via: 'get'
  match '/signout',   to: 'sessions#destroy',     via: 'delete'
  match '/dashboard', to: 'users#show',           via: 'get'
  match '/profile',   to: 'users#edit',           via: 'get'
  match '/tours',     to: 'tours#index',          via: 'get'

  match 'tours/b/:id', to: 'tours#show_branded',  via: 'get'

  get "*any", via: :all, to: "errors#not_found" # to capture any request that doesn't match a routing rule above

end

app/models/tour.rb
class Tour < ActiveRecord::Base
	belongs_to :user
	has_many :photos, :inverse_of => :tour, dependent: :destroy # Added 'inverse_of' on 4/29, from Hasnan Tut
	accepts_nested_attributes_for :photos, allow_destroy: true # Added on 4/29, from Hasnan Tut for multi-photo uploads
	has_many :leads
	has_one :agent
	
	geocoded_by :address
	after_validation :geocode
	default_scope -> { order('created_at DESC') }
	scope :recent_tours, order("created_at desc").limit(5)
	
	validates	:user_id, presence: true
	validates :address, presence: true
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController

	before_action :authenticate_user!, :except => [:show, :show_branded, :sample_tour1, :sample_tour2]
	before_action :correct_user, :except => [:index, :new, :create, :show, :show_branded, :sample_tour1, :sample_tour2]
	before_action :find_tour, :only => [:show, :show_branded, :edit, :update, :destroy, :delete_photos]
	before_action :find_tour_agents, only: [:show, :show_branded]
	before_action :find_user, :only => [:index, :new]
	before_action :create_agent_list, only: [:new, :edit]
	before_action :check_for_tour_credit, only: [:create]
	after_action :remove_tour_credit, only: [:create]

	def index
		@tours = @user.tours.page(params[:page]).per_page(20)
	end

	def show
		@photos = @tour.photos.where(processed: true).order(:position)
		@bg_photo = @photos[0]
		@hash = Gmaps4rails.build_markers(@tour) do |tour, marker|
  			marker.lat tour.latitude
  			marker.lng tour.longitude
		end
		set_tour_theme
	end

	def show_branded
		@photos = @tour.photos.where(processed: true).order(:position)
		@bg_photo = @photos[0]
		@lead = Lead.new
		@hash = Gmaps4rails.build_markers(@tour) do |tour, marker|
  			marker.lat tour.latitude
  			marker.lng tour.longitude
		end
		@branded = true
		set_tour_theme
	end

	def sample_tour1
		@tour = Tour.find(12)
		@photos = @tour.photos.where(processed: true).order(:position)
		@bg_photo = @photos[0]
		@hash = Gmaps4rails.build_markers(@tour) do |tour, marker|
  			marker.lat tour.latitude
  			marker.lng tour.longitude
		end
		render template: 'tours/sample_tour', layout: 'tour-default/tour-default'
	end

	def sample_tour2
		@tour = Tour.find(12)
		@photos = @tour.photos.where(processed: true).order(:position)
		@bg_photo = @photos[0]
		@hash = Gmaps4rails.build_markers(@tour) do |tour, marker|
  			marker.lat tour.latitude
  			marker.lng tour.longitude
		end
		render template: 'tours/sample_tour', layout: 'tour-graphista/tour-graphista'
	end

	def new
		@tour = Tour.new({:user_id => current_user.id})
	end

	def create
		@tour = current_user.tours.build(tour_params)
		if @tour.save
			flash[:success] = "Tour created for '#{@tour.address}'. Next, let's add some photos!"
			redirect_to edit_tour_path(id: @tour.id)
		else
			flash[:danger] = 'Could not create tour.'
			redirect_to root_url
		end
	end

	def edit
		# @user = @tour.user_id
		@photo = Photo.new({tour_id: @tour.id})
		@photos = @tour.photos.order(:position)
	end

	def update
	    if @tour.update_attributes(tour_params)
	    	if params[:photos]
		    	params[:photos]['photo'].each do |photo|
		    		@photo = @tour.photos.create!(:photo => photo, :tour_id => @tour.id)
		    	end
		    end
	    flash[:success] = "Tour for '#{@tour.address}' updated!"
        redirect_to edit_tour_path(id: @tour.id)
	    else
	      flash[:danger] = 'Could not update tour.'
		  redirect_to :back
	    end
	end

	def destroy
		@tour.inactive = true
		@tour.save
		@tour.delay.destroy
		flash[:success] = "'#{@tour.address}' tour has been deleted."
		redirect_to :back
	end

	def delete_photos
    @tour.photos.delete_all
    redirect_to :back
  end

	private

	  	# BEFORE FILTERS

	    def correct_user
	      unless current_user.id.to_i == Tour.find(params[:id]).user_id.to_i
	        redirect_to root_url
	      end
	    end

	  	def find_tour
      	@tour = Tour.find(params[:id])
    	end

	  	def find_user
	  		@user = User.find(current_user.id)
    	end

    	def find_tour_agents
    		# real estate agent
    		if @tour.agent_id.present?
    			@tour_agent = Agent.find(@tour.agent_id)
    		else
    			@tour_agent = @tour.user
    		end

    		# photographer
    		if @tour.photographer_id.present?
    			@tour_photographer = Agent.find(@tour.photographer_id)
    		else
    			@tour_photographer = @tour.user
    		end

    	end

    	def create_agent_list
    		@agent_list = current_user.agents.all
    	end

    	def set_tour_theme
			tour_theme = @tour.theme
			case tour_theme
			when 1
				render layout: 'tour-default/tour-default'
			when 2
				render layout: 'tour-graphista/tour-graphista'
			else
				render layout: 'tour-default/tour-default'
			end
    	end

    	def check_for_tour_credit
    		unless current_user.tour_available?
    			flash[:danger] = 'No tour credits available. Purchase one below to proceed.'
    			redirect_to dashboard_path
    		end
    	end

    	def remove_tour_credit
    		unless current_user.tours_unlimited
    			current_user.tour_credits = current_user.tour_credits - 1
    			current_user.save
    		end
    	end

    	def tour_params
	  		params.require(:tour).permit( :user_id, 
	  									  :address, 
	  									  :city, 
	  									  :state, 
	  									  :zip, 
	  									  :description, 
	  									  :price, 
	  									  :beds, 
	  									  :baths, 
	  									  :home_size, 
	  									  :lot_size, 
	  									  :year_built, 
	  									  :autoplay_music, 
	  									  :music_selection, 
	  									  :theme, 
	  									  :inactive,
	  									  :scheduler,
	  									  :scheduler_auto_display,
	  									  :agent_id,
	  									  :show_photographer_info,
	  									  :photographer_id,
	  									  :video,
	  									  photos_attributes: [:id, :tour_id, :photo] )
	  	end

end

app/helpers/tours_helper.rb
module ToursHelper

	def website_helper(website)
		if website.length > 40
			'Website'
		else
			website
		end
	end

	def email_helper(email)
		if email.length > 40
			'Email'
		else
			email
		end
	end

	def photo_filename_limiter(filename)
		if filename.length > 18
			filename[0...16] + '...'
		else
			filename
		end
	end

end

app/views/tours/partials/_home_info.html.erb
<div class="container-fluid">
	
	<%= bootstrap_form_for(@tour, :html => { :multipart => true }) do |f| %>
		<%= render 'shared/tour_error_messages' %>

		<div class="row">
			<div class="float-right">
				<%= f.submit "Save Changes", class: "btn btn-lg btn-primary", :'data-no-turbolink' => "true" %>
			</div>
		</div>

		<div class="row">

			<div class="col-md-4">
					<h2 class="center">Address:</h2>
					<br />
					<%= f.text_field :address, hide_label: true, placeholder: 'Street Address', required: true %>
					<%= f.text_field :city, layout: :inline, hide_label: true, placeholder: 'City' %>
					<%= f.select :state, [
				      ['(select)', ' '],
				      ['Alabama', 'AL'],
				      ['Alaska', 'AK'],
				      ['Arizona', 'AZ'],
				      ['Arkansas', 'AR'],
				      ['California', 'CA'],
				      ['Colorado', 'CO'],
				      ['Connecticut', 'CT'],
				      ['Delaware', 'DE'],
				      ['District of Columbia', 'DC'],
				      ['Florida', 'FL'],
				      ['Georgia', 'GA'],
				      ['Hawaii', 'HI'],
				      ['Idaho', 'ID'],
				      ['Illinois', 'IL'],
				      ['Indiana', 'IN'],
				      ['Iowa', 'IA'],
				      ['Kansas', 'KS'],
				      ['Kentucky', 'KY'],
				      ['Louisiana', 'LA'],
				      ['Maine', 'ME'],
				      ['Maryland', 'MD'],
				      ['Massachusetts', 'MA'],
				      ['Michigan', 'MI'],
				      ['Minnesota', 'MN'],
				      ['Mississippi', 'MS'],
				      ['Missouri', 'MO'],
				      ['Montana', 'MT'],
				      ['Nebraska', 'NE'],
				      ['Nevada', 'NV'],
				      ['New Hampshire', 'NH'],
				      ['New Jersey', 'NJ'],
				      ['New Mexico', 'NM'],
				      ['New York', 'NY'],
				      ['North Carolina', 'NC'],
				      ['North Dakota', 'ND'],
				      ['Ohio', 'OH'],
				      ['Oklahoma', 'OK'],
				      ['Oregon', 'OR'],
				      ['Pennsylvania', 'PA'],
				      ['Puerto Rico', 'PR'],
				      ['Rhode Island', 'RI'],
				      ['South Carolina', 'SC'],
				      ['South Dakota', 'SD'],
				      ['Tennessee', 'TN'],
				      ['Texas', 'TX'],
				      ['Utah', 'UT'],
				      ['Vermont', 'VT'],
				      ['Virginia', 'VA'],
				      ['Washington', 'WA'],
				      ['West Virginia', 'WV'],
				      ['Wisconsin', 'WI'],
				      ['Wyoming', 'WY']
				    ], layout: :inline, hide_label: true
				%>
				<%= f.text_field :zip, layout: :inline, hide_label: true, placeholder: 'Zip' %>

				<div class="tour-instructions-box mar-top30">
				  <i class="fa fa-map-marker"></i>Maps are generated automatically based on the address. If you need to correct a map location, please contact <a href="mailto:support@showandtour.com">support@showandtour.com</a>.
				</div>

			</div>

			<div class="col-md-4">
				<h2 class="center">Description:</h2>
				<br />
				<%= f.text_area :description, size: "24x10", hide_label: true %>
			</div>

			<div class="col-md-4" id="field-group-padding">
				<h2 class="center">Other Info:</h2>
				<br />
				<%= f.text_field :price, layout: :horizontal, label_col: "col-sm-6", control_col: "col-sm-6" %>
				<%= f.text_field :beds, layout: :horizontal, label_col: "col-sm-6", control_col: "col-sm-6" %>
				<%= f.text_field :baths, layout: :horizontal, label_col: "col-sm-6", control_col: "col-sm-6" %>
				<%= f.number_field :home_size, layout: :horizontal, label_col: "col-sm-6", control_col: "col-sm-6", label: "Home Size (sq ft)" %>
				<%= f.text_field :lot_size, layout: :horizontal, label_col: "col-sm-6", control_col: "col-sm-6", label: "Lot Size (acres)" %>
				<%= f.text_field :year_built, layout: :horizontal, label_col: "col-sm-6", control_col: "col-sm-6" %>
			</div>
		</div> <!-- /.row -->

		<br />
		<hr>

		<div class="row">
			<!-- REAL ESTATE AGENT INFO -->
			<div class="col-md-4 col-md-offset-4">
				<h2 class="grey"><i class="fa fa-user icon-pad"></i>Listing Agent & Photographer</h2>
				<br>
				<div class="float-right">
				      <%= link_to "Add New Agent", new_agent_path, target: "_blank" %>
				</div>
				<%= f.collection_select :agent_id, current_user.agents.all, :id, :full_name, {include_blank: "#{current_user.first_name} #{current_user.last_name} (use my info)"} %>
				<br>
				<%= f.check_box :show_photographer_info, layout: :horizontal, label_col: "col-sm-6", control_col: "col-sm-6", label: 'Show photographer info on tours' %>
				<%= f.collection_select :photographer_id, current_user.agents.all, :id, :full_name, {include_blank: "#{current_user.first_name} #{current_user.last_name} (use my info)"} %>
				<div class="tour-instructions-box mar-top30">
					<i class="fa fa-info-circle"></i>The "branded" tour will include the listing real estate agent's information. If selected, both branded and unbranded tours will show the photographer's information.
				</div>

			</div>

			<!-- PHOTOGRAPHER INFO -->
			<div class="col-md-4 col-md-offset-1">

			</div>
		</div> <!-- /.row -->

		<br /><br /><br />

		<div class="row">
			<div class="float-right">
				<%= f.submit "Save Changes", class: "btn btn-lg btn-primary", :'data-no-turbolink' => "true" %>
			</div>

		<% end %>
	</div> <!-- /.row -->
</div> <!-- /.container -->

app/views/tours/partials/_photos.html.erb
<div class="row">
	<div class="col-md-6">

		<!-- Photo Uploader -->
		<h3><i class="fa fa-camera icon-pad"></i>Upload Photos</h3>

		<%= render 'shared/photo_error_messages' %>
		<%= s3_uploader_form callback_url: tour_photos_url(tour_id: @tour.id),
		  id: "s3_uploader",
			callback_param: "photo[direct_upload_url]",
			expiration: 24.hours.from_now.utc.iso8601,
			max_file_size: 100.megabytes do %>
			<%= file_field_tag :file, multiple: true %>
		<% end %>

		<div class="alert alert-info mar-top20" style="display:inline-block">
			<i class="fa fa-warning" style="margin-right: 10px;"></i>
			<strong>1280px by 960px</strong> photos (or larger) are recommended for best results.
		</div>

		<div id="photos-uploading-warning">
			<div class="alert alert-notice" style="display: inline-block;">Please do not refresh or close this page until all photos have uploaded.</div>
		</div>

		<div id="uploads_container"></div>
		<script id="template-upload" type="text/x-tmpl">
			<div id="upload_{%=o.unique_id%}" class="upload">
			  <h5>{%=o.name%}</h5>
			  <div class="progress progress-striped active"><div class="bar" style="width: 0%"></div></div>
			</div>
		</script>
		<!-- end photo uploader -->

		<!-- New Photos Uploading -->
		<div id="new-photos-processing-wrapper">
			<ul id="new-photos-processing"></ul>
		</div>

		<!-- if any photos processing -->
		<% if @tour.photos.where("processed = ?", "false").any? %>
		<div class="alert alert-info" style="display: inline-block;">Some of your photos are still processing. Refresh the page to check the progress.</div>
		<% end %>
	</div>

	<div class="col-md-6">
		<!-- photo-related instructions -->
		<% if @tour.photos.any? %>
			<div class="tour-instructions-box mar-top20">
				<i class="fa fa-arrows"></i>Change the order of photos via drag-and-drop with the arrows to the left. <br />
				<i class="fa fa-tag"></i>To add a label to a photo, click "add label", enter text, and hit return. <br />
				<i class="fa fa-photo"></i>The first photo in your list will be used as the tour's background image.
			</div>
		<% end %>
	</div>

</div> <!-- /.row -->

<hr>

<div class="row">
	<div class="col-md-12">

		<!-- if no photos have been added -->
		<% unless @tour.photos.any? %>
			<div id="no-photos-found">No photos have been added.</div>
		<% end %>

		<!-- list of uploaded photos -->
		<ul id="photo-preview-list" class="mar-top20" data-update-url="<%= sort_photos_url %>">
			<% @photos.each do |photo| %>
				<%= content_tag_for :li, photo do %>
					<div class="drag-handle">

						<!-- photo -->
						<% if photo.processed %>
							<div class="photo-preview-photo"><%= image_tag photo.upload.url(:thumb) %></div>
						<% else %>
							<div class="photo-preview-photo"><%= image_tag "photo-processing.png" %></div>
						<% end %>
					</div>

					<!-- delete btn -->
					<%= link_to "X", tour_photo_path(tour_id: photo.tour.id, id: photo.id), method: :delete, data: { confirm: "Are you sure you want to delete this photo?" }, class: "btn btn-danger btn-xs photo-delete-btn" %>

					<!-- magnify btn -->

					<a href="#" data-featherlight="<%= photo.upload.url(:slider).to_s %>">
						<div class="photo-magnify-btn btn btn-xs btn-default"><i class="fa fa-search-plus"></i></div>
					</a>

					<!-- filename -->
					<div class="photo-preview-title">
						<span class="photo-preview-filename"><%= photo_filename_limiter(photo.upload.original_filename) %></span>
					</div>

					<!-- label -->
					<div class="photo-preview-label">
						<span class="rest-in-place" data-url="/photos/<%= photo.id %>" data-object="photo" data-attribute="label">
							<%= photo.label || "(add label)" %>
						</span>
					</div>
					
				<% end %>
			<% end %>

		</ul>

		<% if @tour.photos.any? %>
			<%= link_to "Delete All", "/tours/#{@tour.id}/delete_photos", :method => :get, data: { confirm: "Are you sure you want to permanentaly delete ALL photos? This cannot be undone." }, class: "btn btn-danger btn-sm delete-all-photos-btn" %>
		<% end %>

	</div>
</div> <!-- /.row -->

<hr>

<div class="row">

	<div class="col-md-6">
		<%= bootstrap_form_for(@tour, :html => { :multipart => true }) do |f| %>
			<h3><i class="fa fa-film icon-pad"></i>Video:</h3>
			<p>Simply paste the embed code from YouTube or Vimeo (<a href="/blog/videos" target="_blank">learn more</a>)</p>
			<%= f.text_area :video, size: "24x3", hide_label: true %>
		<% end %>
	</div>

</div> <!-- /.row -->

app/views/tours/partials/_tour_settings.html.erb
<%= bootstrap_form_for(@tour, :html => { :multipart => true }) do |f| %> <!-- TOUR INFO FORM -->

	<div class="row">
		<div class="float-right">
			<%= f.submit "Save Changes", class: "btn btn-lg btn-primary", :'data-no-turbolink' => "true" %>
		</div>
	</div>

	<div class="row mar-top50">
		<div class="col-md-3 col-md-offset-2">
			<h3>Theme</h3>
			<br>
			<div class="choose-theme">
			      <%= f.form_group :theme do %>
			        <%= f.radio_button :theme, 2, label: "Fullscreen" %>
			        <%= f.radio_button :theme, 1, label: "Circles" %>
			      <% end %>
			</div>
		</div>

		<div class="col-md-3">
			<h3>Options</h3>
			<br>
			<%= f.check_box :autoplay_music, layout: :horizontal, label_col: "col-sm-6", control_col: "col-sm-6", label: "Play background music" %>
			<%= f.check_box :scheduler, layout: :horizontal, label_col: "col-sm-6", control_col: "col-sm-6", label: "Use scheduler widget" %>
			<%= f.check_box :scheduler_auto_display, layout: :horizontal, label_col: "col-sm-6", control_col: "col-sm-6", label: "Auto-show lead generation form" %>
		</div>

		<div class="col-md-3">
			<h3>Status</h3>
			<br>
			<%= f.check_box :inactive, layout: :horizontal, label_col: "col-sm-6", control_col: "col-sm-6", label: "Make tour inactive" %>
		</div>
	</div>

<% end %>