config/routes.rb
TourApp::Application.routes.draw do
  resources :agents

  mount StripeEvent::Engine => '/stripe'
  devise_for :users, :controllers => { :registrations => 'users/registrations' }
  devise_scope :user do
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users, :except => [:edit, :show]

  # devise_for :users
  # resources :users
  resources :tours, :except => [:index] do
    resources :photos, only: [:new, :create, :destroy] 
  end

  match '/tours/:id/delete_photos', to: 'tours#delete_photos', via: 'get'

  resources :photos do
    collection { post :sort }  # from railscasts #147... not sure if I need this
  end

  resources :leads, only: [:create, :index]

  resources :charges

  root :to => 'static_pages#home' 

  # Sales Pages
  match '/home',      to: 'static_pages#home' ,     via: 'get'
  match '/features',  to: 'static_pages#features',  via: 'get'
  match '/about',     to: 'static_pages#about',     via: 'get'
  match '/contact',   to: 'static_pages#contact',     via: 'get'
  match '/survey',    to: 'static_pages#survey',    via: 'get'
  match '/signup',    to: 'users#new',              via: 'get'
  match '/sample1',   to: 'tours#sample_tour1',     via: 'get'
  match '/sample2',   to: 'tours#sample_tour2',     via: 'get'

  # Blog
  namespace :blog do
    resources :articles, path: '', only: [:index, :show]
  end

  # App
  match '/signin',    to: 'sessions#new',         via: 'get'
  match '/signout',   to: 'sessions#destroy',     via: 'delete'
  match '/dashboard', to: 'users#show',           via: 'get'
  match '/profile',   to: 'users#edit',           via: 'get'
  match '/tours',     to: 'tours#index',          via: 'get'

  match 'tours/b/:id', to: 'tours#show_branded',  via: 'get'

  get "*any", via: :all, to: "errors#not_found" # to capture any request that doesn't match a routing rule above

end

app/models/tour.rb
class Tour < ActiveRecord::Base
	belongs_to :user
	has_many :photos, :inverse_of => :tour, dependent: :destroy # Added 'inverse_of' on 4/29, from Hasnan Tut
	accepts_nested_attributes_for :photos, allow_destroy: true # Added on 4/29, from Hasnan Tut for multi-photo uploads
	has_many :leads
	has_one :agent
	
	geocoded_by :address
	after_validation :geocode
	default_scope -> { order('created_at DESC') }
	scope :recent_tours, order("created_at desc").limit(5)
	
	validates	:user_id, presence: true
	validates :address, presence: true
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController

	before_action :authenticate_user!, :except => [:show, :show_branded, :sample_tour1, :sample_tour2]
	before_action :correct_user, :except => [:index, :new, :create, :show, :show_branded, :sample_tour1, :sample_tour2]
	before_action :find_tour, :only => [:show, :show_branded, :edit, :update, :destroy, :delete_photos]
	before_action :find_tour_agents, only: [:show, :show_branded]
	before_action :find_user, :only => [:index, :new]
	before_action :create_agent_list, only: [:new, :edit]
	before_action :check_for_tour_credit, only: [:create]
	after_action :remove_tour_credit, only: [:create]

	def index
		@tours = @user.tours.page(params[:page]).per_page(20)
	end

	def show
		@photos = @tour.photos.where(processed: true).order(:position)
		@bg_photo = @photos[0]
		@hash = Gmaps4rails.build_markers(@tour) do |tour, marker|
  			marker.lat tour.latitude
  			marker.lng tour.longitude
		end
		set_tour_theme
	end

	def show_branded
		@photos = @tour.photos.where(processed: true).order(:position)
		@bg_photo = @photos[0]
		@lead = Lead.new
		@hash = Gmaps4rails.build_markers(@tour) do |tour, marker|
  			marker.lat tour.latitude
  			marker.lng tour.longitude
		end
		@branded = true
		set_tour_theme
	end

	def sample_tour1
		@tour = Tour.find(12)
		@photos = @tour.photos.where(processed: true).order(:position)
		@bg_photo = @photos[0]
		@hash = Gmaps4rails.build_markers(@tour) do |tour, marker|
  			marker.lat tour.latitude
  			marker.lng tour.longitude
		end
		render template: 'tours/sample_tour', layout: 'tour-default/tour-default'
	end

	def sample_tour2
		@tour = Tour.find(12)
		@photos = @tour.photos.where(processed: true).order(:position)
		@bg_photo = @photos[0]
		@hash = Gmaps4rails.build_markers(@tour) do |tour, marker|
  			marker.lat tour.latitude
  			marker.lng tour.longitude
		end
		render template: 'tours/sample_tour', layout: 'tour-graphista/tour-graphista'
	end

	def new
		@tour = Tour.new({:user_id => current_user.id})
	end

	def create
		@tour = current_user.tours.build(tour_params)
		if @tour.save
			flash[:success] = "Tour created for '#{@tour.address}'. Next, let's add some photos!"
			redirect_to edit_tour_path(id: @tour.id)
		else
			flash[:danger] = 'Could not create tour.'
			redirect_to root_url
		end
	end

	def edit
		# @user = @tour.user_id
		@photo = Photo.new({tour_id: @tour.id})
		@photos = @tour.photos.order(:position)
	end

	def update
	    if @tour.update_attributes(tour_params)
	    	if params[:photos]
		    	params[:photos]['photo'].each do |photo|
		    		@photo = @tour.photos.create!(:photo => photo, :tour_id => @tour.id)
		    	end
		    end
	    flash[:success] = "Tour for '#{@tour.address}' updated!"
        redirect_to edit_tour_path(id: @tour.id)
	    else
	      flash[:danger] = 'Could not update tour.'
		  redirect_to :back
	    end
	end

	def destroy
		@tour.inactive = true
		@tour.save
		@tour.delay.destroy
		flash[:success] = "'#{@tour.address}' tour has been deleted."
		redirect_to :back
	end

	def delete_photos
    @tour.photos.delete_all
    redirect_to :back
  end

	private

	  	# BEFORE FILTERS

	    def correct_user
	      unless current_user.id.to_i == Tour.find(params[:id]).user_id.to_i
	        redirect_to root_url
	      end
	    end

	  	def find_tour
      	@tour = Tour.find(params[:id])
    	end

	  	def find_user
	  		@user = User.find(current_user.id)
    	end

    	def find_tour_agents
    		# real estate agent
    		if @tour.agent_id.present?
    			@tour_agent = Agent.find(@tour.agent_id)
    		else
    			@tour_agent = @tour.user
    		end

    		# photographer
    		if @tour.photographer_id.present?
    			@tour_photographer = Agent.find(@tour.photographer_id)
    		else
    			@tour_photographer = @tour.user
    		end

    	end

    	def create_agent_list
    		@agent_list = current_user.agents.all
    	end

    	def set_tour_theme
			tour_theme = @tour.theme
			case tour_theme
			when 1
				render layout: 'tour-default/tour-default'
			when 2
				render layout: 'tour-graphista/tour-graphista'
			else
				render layout: 'tour-default/tour-default'
			end
    	end

    	def check_for_tour_credit
    		unless current_user.tour_available?
    			flash[:danger] = 'No tour credits available. Purchase one below to proceed.'
    			redirect_to dashboard_path
    		end
    	end

    	def remove_tour_credit
    		unless current_user.tours_unlimited
    			current_user.tour_credits = current_user.tour_credits - 1
    			current_user.save
    		end
    	end

    	def tour_params
	  		params.require(:tour).permit( :user_id, 
	  									  :address, 
	  									  :city, 
	  									  :state, 
	  									  :zip, 
	  									  :description, 
	  									  :price, 
	  									  :beds, 
	  									  :baths, 
	  									  :home_size, 
	  									  :lot_size, 
	  									  :year_built, 
	  									  :autoplay_music, 
	  									  :music_selection, 
	  									  :theme, 
	  									  :inactive,
	  									  :scheduler,
	  									  :scheduler_auto_display,
	  									  :agent_id,
	  									  :show_photographer_info,
	  									  :photographer_id,
	  									  :video,
	  									  photos_attributes: [:id, :tour_id, :photo] )
	  	end

end

app/helpers/tours_helper.rb
module ToursHelper

	def website_helper(website)
		if website.length > 40
			'Website'
		else
			website
		end
	end

	def email_helper(email)
		if email.length > 40
			'Email'
		else
			email
		end
	end

	def photo_filename_limiter(filename)
		if filename.length > 18
			filename[0...16] + '...'
		else
			filename
		end
	end

end

app/views/tours/_form.html.erb
<h4>Address:</h4>
<%= f.text_field :address, hide_label: true, placeholder: 'Street Address', required: true %>

<%= f.text_field :city, layout: :inline, hide_label: true, placeholder: 'City' %>

<%= f.select :state, [
      ['(select)', ' '],
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ], layout: :inline, hide_label: true
%>

<%= f.text_field :zip, layout: :inline, hide_label: true, placeholder: 'Zip' %>

<br />

<div class="tour-instructions-box">
      <i class="fa fa-map-marker"></i>Maps are generated automatically based on the address. If you need to correct a map location, please contact <a href="mailto:support@showandtour.com">support@showandtour.com</a>.
</div>

<br />

<h4>Description:</h4>

<%= f.text_area :description, size: "24x6", hide_label: true %>

<br />

<h4>Other Info:</h4>

<div id="field-group-padding">
      <%= f.text_field :price, layout: :horizontal, label_col: "col-sm-4", control_col: "col-sm-8" %>
      <%= f.text_field :beds, layout: :horizontal, label_col: "col-sm-4", control_col: "col-sm-8" %>
      <%= f.text_field :baths, layout: :horizontal, label_col: "col-sm-4", control_col: "col-sm-8" %>
      <%= f.number_field :home_size, layout: :horizontal, label_col: "col-sm-4", control_col: "col-sm-8" %>
      <%= f.text_field :lot_size, layout: :horizontal, label_col: "col-sm-4", control_col: "col-sm-8" %>
      <%= f.text_field :year_built, layout: :horizontal, label_col: "col-sm-4", control_col: "col-sm-8" %>
</div>

<br />

<h2 class="grey"><i class="fa fa-film icon-pad"></i>Video:</h2>
<p>Simply paste the embed code from YouTube or Vimeo (<a href="/blog/videos" target="_blank">learn more</a>)</p>
<%= f.text_area :video, size: "24x3", hide_label: true %>

<br />

<h2 class="grey"><i class="fa fa-user icon-pad"></i>Tour Agent:</h2>

<div class="tour-instructions-box">
      The "branded" tour will include the real estate agent's information. It will display your information by default, but if you need to use a different agent, select them from your list of agents. 
</div>

<div class="float-right">
      <%= link_to "Add New Agent", new_agent_path, target: "_blank" %>
</div>

<%= f.collection_select :agent_id, current_user.agents.all, :id, :full_name, {include_blank: "#{current_user.first_name} #{current_user.last_name} (use my info)"} %>

<h2 class="grey"><i class="fa fa-camera icon-pad"></i>Photographer Info:</h2>

<%= f.check_box :show_photographer_info, layout: :horizontal, label_col: "col-sm-6", control_col: "col-sm-6", label: 'Include "Photo Info" icon/information' %>

<%= f.collection_select :photographer_id, current_user.agents.all, :id, :full_name, {include_blank: "#{current_user.first_name} #{current_user.last_name} (use my info)"} %>

<h2 class="grey"><i class="fa fa-cog icon-pad"></i>Tour Options:</h2>

<div class="choose-theme">
      <%= f.form_group :theme, label: { text: "Theme:"} do %>
        <%= f.radio_button :theme, 2, label: "Fullscreen" %>
        <%= f.radio_button :theme, 1, label: "Circles" %>
      <% end %>
</div>
<%= f.check_box :autoplay_music, layout: :horizontal, label_col: "col-sm-6", control_col: "col-sm-6", label: "Play background music" %>
<%= f.check_box :scheduler, layout: :horizontal, label_col: "col-sm-6", control_col: "col-sm-6", label: "Use scheduler widget" %>
<%= f.check_box :scheduler_auto_display, layout: :horizontal, label_col: "col-sm-6", control_col: "col-sm-6", label: "Auto-show lead generation form" %>
<%= f.check_box :inactive, layout: :horizontal, label_col: "col-sm-6", control_col: "col-sm-6", label: "Make tour inactive" %>

app/views/tours/_tour.html.erb
<tr <%= tour.inactive ? 'class=inactive' : "" %>>
  <td><%= tour.created_at.strftime("%m/%d/%y") %></td>
  <td><%= tour.address %></td>
  <td>
    <% if tour.city.blank? | tour.state.blank? %>
      <%= "#{tour.city} #{tour.state} #{tour.zip}" %>
    <% else %>
      <%= "#{tour.city}, #{tour.state} #{tour.zip}" %>
    <% end %>
  </td>
  <td><%= number_to_currency(tour.price, precision: 0) %></td>
  <% if tour.inactive %>
    <td>(inactive)</td>
  <% elsif tour.photos.any? %>
    <td>
      Unbranded: <%= link_to "http://www.showandtour.com/tours/#{tour.id}", tour_path(tour.id), :target => '_blank' %> <br />
      Branded:  <%= link_to "http://www.showandtour.com/tours/b/#{tour.id}", "../tours/b/#{tour.id}", :target => '_blank' %>
    </td>
  <% else %>
    <td>(add photos to create tour links)</td>
  <% end %>
  <td>
    <%= link_to "Edit", edit_tour_path(tour.id), class: "btn btn-info btn-xs btn-spacer" %>
  	<% @delete_object = tour %>
  	<%= link_to "X", @delete_object, method: :delete, data: { confirm: "Are you sure you want to PERMANENTLY delete the tour for #{tour.address}?" }, title: @delete_object.address, class: "btn btn-danger btn-xs btn-spacer" %>
    </td>
</tr>

app/views/tours/_x_form.html.erb
<h4>Address:</h4>
<%= f.text_field :address, hide_label: true, placeholder: 'Street Address', required: true %>

<%= f.text_field :city, layout: :inline, hide_label: true, placeholder: 'City' %>

<%= f.select :state, [
      ['(select)', ' '],
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ], layout: :inline, hide_label: true
%>

<%= f.text_field :zip, layout: :inline, hide_label: true, placeholder: 'Zip' %>

<br />

<div class="tour-instructions-box">
      <i class="fa fa-map-marker"></i>Maps are generated automatically based on the address. If you need to correct a map location, please contact <a href="mailto:support@showandtour.com">support@showandtour.com</a>.
</div>

<br />

<h4>Description:</h4>

<%= f.text_area :description, size: "24x6", hide_label: true %>

<br />

<h4>Other Info:</h4>

<div id="field-group-padding">
      <%= f.text_field :price, layout: :horizontal, label_col: "col-sm-4", control_col: "col-sm-8" %>
      <%= f.text_field :beds, layout: :horizontal, label_col: "col-sm-4", control_col: "col-sm-8" %>
      <%= f.text_field :baths, layout: :horizontal, label_col: "col-sm-4", control_col: "col-sm-8" %>
      <%= f.number_field :home_size, layout: :horizontal, label_col: "col-sm-4", control_col: "col-sm-8" %>
      <%= f.text_field :lot_size, layout: :horizontal, label_col: "col-sm-4", control_col: "col-sm-8" %>
      <%= f.text_field :year_built, layout: :horizontal, label_col: "col-sm-4", control_col: "col-sm-8" %>
</div>

<br />

<h2 class="grey"><i class="fa fa-film icon-pad"></i>Video:</h2>
<p>Simply paste the embed code from YouTube or Vimeo (<a href="/blog/videos" target="_blank">learn more</a>)</p>
<%= f.text_area :video, size: "24x3", hide_label: true %>

<br />

<h2 class="grey"><i class="fa fa-user icon-pad"></i>Tour Agent:</h2>

<div class="tour-instructions-box">
      The "branded" tour will include the real estate agent's information. It will display your information by default, but if you need to use a different agent, select them from your list of agents. 
</div>

<div class="float-right">
      <%= link_to "Add New Agent", new_agent_path, target: "_blank" %>
</div>

<%= f.collection_select :agent_id, current_user.agents.all, :id, :full_name, {include_blank: "#{current_user.first_name} #{current_user.last_name} (use my info)"} %>

<h2 class="grey"><i class="fa fa-camera icon-pad"></i>Photographer Info:</h2>

<%= f.check_box :show_photographer_info, layout: :horizontal, label_col: "col-sm-6", control_col: "col-sm-6", label: 'Include "Photo Info" icon/information' %>

<%= f.collection_select :photographer_id, current_user.agents.all, :id, :full_name, {include_blank: "#{current_user.first_name} #{current_user.last_name} (use my info)"} %>

<h2 class="grey"><i class="fa fa-cog icon-pad"></i>Tour Options:</h2>

<div class="choose-theme">
      <%= f.form_group :theme, label: { text: "Theme:"} do %>
        <%= f.radio_button :theme, 2, label: "Fullscreen" %>
        <%= f.radio_button :theme, 1, label: "Circles" %>
      <% end %>
</div>
<%= f.check_box :autoplay_music, layout: :horizontal, label_col: "col-sm-6", control_col: "col-sm-6", label: "Play background music" %>
<%= f.check_box :scheduler, layout: :horizontal, label_col: "col-sm-6", control_col: "col-sm-6", label: "Use scheduler widget" %>
<%= f.check_box :scheduler_auto_display, layout: :horizontal, label_col: "col-sm-6", control_col: "col-sm-6", label: "Auto-show lead generation form" %>
<%= f.check_box :inactive, layout: :horizontal, label_col: "col-sm-6", control_col: "col-sm-6", label: "Make tour inactive" %>

app/views/tours/edit.html.erb
<% provide(:title, 'Edit Tour') %>

<div class="container-fluid">
	<h1><%= @tour.address %></h1>
	<hr />
	<div class="row tour-edit-subhead">
		<div class="col-sm-1 col-xs-offset-1 margin-top">
			<%= link_to "<- Back to All Tours", tours_path(user_id: @tour.user_id), class: "btn" %>
		</div>

		
		<div class="col-sm-6 col-sm-offset-4">
			<div class="row">
			<div class="col-xs-4">
				<h2>View Tour:</h2>
			</div>
			<div class="col-xs-8 mar-top15">
				<% if @tour.inactive %>
				<div class="tour-links-inactive">
					(tour is currently set as inactive)
				</div>
				<% elsif @tour.photos.any? %>
				<div class="tour-link">Unbranded: <%= link_to "http://www.showandtour.com/tours/#{@tour.id}", tour_path(@tour.id), :target => '_blank' %></div>
				<div class="tour-link">Branded: <%= link_to "http://www.showandtour.com/tours/b/#{@tour.id}", "/tours/b/#{@tour.id}", :target => '_blank' %></div>
				<% else %>
				<div class="mar-top15">Add photos in order to view this tour</div>
				<% end %>
			</div>
			</div>
		</div>
	</div>
	<hr />


	<div class="row tour-edit-body">

		<div class="col-md-10 col-md-offset-1">

  <!-- Nav tabs -->
  <ul class="nav nav-pills tour-edit-tabs" role="tablist" id="edit-tour-tabs">
    <li role="presentation" class="active">
    	<a href="#info" aria-controls="info" role="tab" data-toggle="pill">
    		<i class="fa fa-home icon-pad"></i>Property & Listing Info
    	</a>
    </li>
    <li role="presentation">
    	<a href="#photos" aria-controls="photos" role="tab" data-toggle="pill">
    		<i class="fa fa-photo"></i> Photos & Video
    	</a>
    </li>
    <li role="presentation">
    	<a href="#settings" aria-controls="settings" role="tab" data-toggle="pill">
    		<i class="fa fa-cog icon-pad"></i>Settings
    	</a>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="info">
    	<%= render 'tours/partials/home_info' %>
    </div>

    <div role="tabpanel" class="tab-pane" id="photos">
			<%= render 'tours/partials/photos' %>
    </div>

    <div role="tabpanel" class="tab-pane" id="settings">
    	<%= render 'tours/partials/tour_settings' %>
    </div>
  </div>

</div>


	</div>
</div> <!-- /.container-fluid -->

app/views/tours/index.html.erb
<% provide(:title, 'My Tours') %>
<div class="container">
	<div class="dashboard-tours">
	    <h1 class="tours_title">My Tours</h1>
        <% if @user.tour_available? %>
            <%= link_to "Create New Tour", new_tour_path(user_id: @user.id), class: "btn btn-primary btn-lg float-right", :'data-no-turbolink' => "true" %>
        <% else %>
            <div class="float-right">
                To create a new tour:
                <div class="mar-top10 mar-bot20">            
                  <%= render "layouts/payment_btn" %>
                </div>
            </div>
        <% end %>
        <% if @user.tours.any? %>
        <div class="table-responsive">
            <table class="tours table">
                <thead>
            	<tr id="no-background">
            		<th>Created</th>
            		<th>Address</th>
            		<th>City</th>
            		<th>Price</th>
                    <th>Tour Links</th>
                    <th> </th>
            	</tr>
                </thead>
                
                <tbody>
                <%= render @tours %>
                </tbody>
            </table>
        </div>
        <%= will_paginate @tours, renderer: BootstrapPagination::Rails %>
        <% else %>
        <h1 class="no_tours_found"> 
            No tours found! 
            <% if @user.tour_available? %>
                <%= link_to "Create one.", new_tour_path(user_id: @user.id), :'data-no-turbolink' => "true" %></h1>
            <% end %>
        <% end %>
	</div>
</div>

app/views/tours/new.html.erb
<% provide(:title, 'Create Tour') %>
<h1><i class="fa fa-edit" style="margin-right: 15px;"></i>Create a Tour</h1>

<div class="container">
<div class="row">

	<%= bootstrap_form_for(@tour, user_id: @user.id) do |f| %>
	<%= render 'shared/tour_error_messages' %>

	<div class="col-md-4 col-md-offset-4">
		<br />
		<%= f.text_field :address, hide_label: true, placeholder: 'Street Address', required: true %>
		<%= f.text_field :city, layout: :inline, hide_label: true, placeholder: 'City' %>
		<%= f.select :state, [
	      ['(select)', ' '],
	      ['Alabama', 'AL'],
	      ['Alaska', 'AK'],
	      ['Arizona', 'AZ'],
	      ['Arkansas', 'AR'],
	      ['California', 'CA'],
	      ['Colorado', 'CO'],
	      ['Connecticut', 'CT'],
	      ['Delaware', 'DE'],
	      ['District of Columbia', 'DC'],
	      ['Florida', 'FL'],
	      ['Georgia', 'GA'],
	      ['Hawaii', 'HI'],
	      ['Idaho', 'ID'],
	      ['Illinois', 'IL'],
	      ['Indiana', 'IN'],
	      ['Iowa', 'IA'],
	      ['Kansas', 'KS'],
	      ['Kentucky', 'KY'],
	      ['Louisiana', 'LA'],
	      ['Maine', 'ME'],
	      ['Maryland', 'MD'],
	      ['Massachusetts', 'MA'],
	      ['Michigan', 'MI'],
	      ['Minnesota', 'MN'],
	      ['Mississippi', 'MS'],
	      ['Missouri', 'MO'],
	      ['Montana', 'MT'],
	      ['Nebraska', 'NE'],
	      ['Nevada', 'NV'],
	      ['New Hampshire', 'NH'],
	      ['New Jersey', 'NJ'],
	      ['New Mexico', 'NM'],
	      ['New York', 'NY'],
	      ['North Carolina', 'NC'],
	      ['North Dakota', 'ND'],
	      ['Ohio', 'OH'],
	      ['Oklahoma', 'OK'],
	      ['Oregon', 'OR'],
	      ['Pennsylvania', 'PA'],
	      ['Puerto Rico', 'PR'],
	      ['Rhode Island', 'RI'],
	      ['South Carolina', 'SC'],
	      ['South Dakota', 'SD'],
	      ['Tennessee', 'TN'],
	      ['Texas', 'TX'],
	      ['Utah', 'UT'],
	      ['Vermont', 'VT'],
	      ['Virginia', 'VA'],
	      ['Washington', 'WA'],
	      ['West Virginia', 'WV'],
	      ['Wisconsin', 'WI'],
	      ['Wyoming', 'WY']
	    ], layout: :inline, hide_label: true
	%>
	<%= f.text_field :zip, layout: :inline, hide_label: true, placeholder: 'Zip' %>
	</div>

</div>


<div class="row">
	<div class="center">
		<%= f.submit "Create Tour", class: "btn btn-large btn-primary", :'data-no-turbolink' => "true" %>
		<% end %>
	</div>
</div>
</div>

app/views/tours/sample_tour.html.erb
<% provide(:title, "Sample Tour") %>

app/views/tours/show.html.erb
<% provide(:title, @tour.address) %>

app/views/tours/show_branded.html.erb
<% provide(:title, @tour.address) %>