config/routes.rb
TourApp::Application.routes.draw do
  resources :agents

  mount StripeEvent::Engine => '/stripe'
  devise_for :users, :controllers => { :registrations => 'users/registrations' }
  devise_scope :user do
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users, :except => [:edit, :show]

  # devise_for :users
  # resources :users
  resources :tours, :except => [:index] do
    resources :photos, only: [:new, :create, :destroy] 
  end

  match '/tours/:id/delete_photos', to: 'tours#delete_photos', via: 'get'

  resources :photos do
    collection { post :sort }  # from railscasts #147... not sure if I need this
  end

  resources :leads, only: [:create, :index]

  resources :charges

  root :to => 'static_pages#home' 

  # Sales Pages
  match '/home',      to: 'static_pages#home' ,     via: 'get'
  match '/features',  to: 'static_pages#features',  via: 'get'
  match '/about',     to: 'static_pages#about',     via: 'get'
  match '/contact',   to: 'static_pages#contact',     via: 'get'
  match '/survey',    to: 'static_pages#survey',    via: 'get'
  match '/signup',    to: 'users#new',              via: 'get'
  match '/sample1',   to: 'tours#sample_tour1',     via: 'get'
  match '/sample2',   to: 'tours#sample_tour2',     via: 'get'

  # Blog
  namespace :blog do
    resources :articles, path: '', only: [:index, :show]
  end

  # App
  match '/signin',    to: 'sessions#new',         via: 'get'
  match '/signout',   to: 'sessions#destroy',     via: 'delete'
  match '/dashboard', to: 'users#show',           via: 'get'
  match '/profile',   to: 'users#edit',           via: 'get'
  match '/tours',     to: 'tours#index',          via: 'get'

  match 'tours/b/:id', to: 'tours#show_branded',  via: 'get'

  get "*any", via: :all, to: "errors#not_found" # to capture any request that doesn't match a routing rule above

end

app/models/blog/article.rb
class Blog::Article
	include ActiveModel::Model
	attr_accessor :title, :content, :created_at, :permalink, :author

	# Used for ATOM-feed id
	def id
		@permalink.to_i
	end

	def content
		remove_yaml_frontmatter_from @content
	end

	def excerpt
		content.split('<!--more-->').first
	end

	def content_full
		content.remove('<!--more-->')
	end

	def has_more_text?
		content != excerpt
	end

	def created_at
		@created_at.to_date
	end

	def to_param
		@permalink.parameterize
	end

	# Query methods
	def self.all
		article_files.reverse.map do |file|
			self.new extract_data_from(file)
		end
	end

	def self.find_by_name(name)
		file = find_file_by(name)
		self.new extract_data_from(file)
	end

	private

	def self.article_files
		sort_by_id Dir.glob(articles_path + '/' + '*.md')
	end

	def self.sort_by_id(files)
		files.sort_by { |x| File.basename(x, '.*').to_i }
	end

	def self.find_file_by(name)
		id = article_files.index { |x| x =~ /#{name}.md/ }
		article_files[id]
	end

	def self.articles_path
		Rails.root.join('app', 'views', 'blog', 'published').to_s
	end

	# Content retrieval
	def self.extract_data_from(file)
		{
			content: File.read(file),
			permalink: File.basename(file, '.*')
		}.merge(yaml_frontmatter_metadata_from(file))
	end

	def self.yaml_frontmatter_metadata_from(file)
		YAML.load_file(file)
	end

	def remove_yaml_frontmatter_from(text)
		text.sub(/^\s*---(.*?)---\s/m, "")
	end
end

app/controllers/blog/articles_controller.rb
class Blog::ArticlesController < ApplicationController
  def index
    @articles = Blog::Article.all
  end

  def show
    @article = Blog::Article.find_by_name(params[:id])
  end
end

app/helpers/blog_helper.rb
module BlogHelper

  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end

  def markdown(text)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: false)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe

  end

end

app/views/blog/articles/_meta.html.erb
<div class="meta">
  <time datetime="<%= article.created_at %>">
    <em><%= l article.created_at, format: :long %></em>
  </time>
</div>

app/views/blog/articles/index.html.erb
<div class="page-header-cover"></div>
<h1 class="page-header-title">Blog</h1>

<div class="container">
  <% @articles.each do |article| %>
    <article>
      <h2>
        <%= link_to article.title, blog_article_path(article) %>
      </h2>
      <%= render partial: "meta", locals: { article: article } %>
      <%= markdown article.excerpt %>
      <% if article.has_more_text? %>
        <p>
          <%= link_to "Continue reading →", blog_article_path(article) %>
        </p>
      <% end %>
    </article>
    <hr>
  <% end %>
</div>

app/views/blog/articles/show.html.erb
<% provide(:title, @article.title) %>

<div class="container">
	<article>
	  <h1>
	    <%= @article.title %>
	  </h1>
	  <div class="text-center">
	  	<%= render partial: "meta", locals: { article: @article } %>
	  </div>
	  <div class="mar-top30">
	  	<%= markdown @article.content_full %>
	  </div>
	  <hr/>
	  <p class="action">
	    <%= link_to "← Back to Overview", blog_articles_path %>
	  </p>
	</article>
</div>