config/routes.rb
TourApp::Application.routes.draw do
  resources :agents

  mount StripeEvent::Engine => '/stripe'
  devise_for :users, :controllers => { :registrations => 'users/registrations' }
  devise_scope :user do
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users, :except => [:edit, :show]

  # devise_for :users
  # resources :users
  resources :tours, :except => [:index] do
    resources :photos, only: [:new, :create, :destroy] 
  end

  match '/tours/:id/delete_photos', to: 'tours#delete_photos', via: 'get'

  resources :photos do
    collection { post :sort }  # from railscasts #147... not sure if I need this
  end

  resources :leads, only: [:create, :index]

  resources :charges

  root :to => 'static_pages#home' 

  # Sales Pages
  match '/home',      to: 'static_pages#home' ,     via: 'get'
  match '/features',  to: 'static_pages#features',  via: 'get'
  match '/about',     to: 'static_pages#about',     via: 'get'
  match '/contact',   to: 'static_pages#contact',     via: 'get'
  match '/survey',    to: 'static_pages#survey',    via: 'get'
  match '/signup',    to: 'users#new',              via: 'get'
  match '/sample1',   to: 'tours#sample_tour1',     via: 'get'
  match '/sample2',   to: 'tours#sample_tour2',     via: 'get'

  # Blog
  namespace :blog do
    resources :articles, path: '', only: [:index, :show]
  end

  # App
  match '/signin',    to: 'sessions#new',         via: 'get'
  match '/signout',   to: 'sessions#destroy',     via: 'delete'
  match '/dashboard', to: 'users#show',           via: 'get'
  match '/profile',   to: 'users#edit',           via: 'get'
  match '/tours',     to: 'tours#index',          via: 'get'

  match 'tours/b/:id', to: 'tours#show_branded',  via: 'get'

  get "*any", via: :all, to: "errors#not_found" # to capture any request that doesn't match a routing rule above

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	after_action :add_tour_credit, only: [:create]

	def new
	end

	def create
	  # Amount in cents
	  @amount = 1200

	  customer = Stripe::Customer.create(
	    :email => 'example@stripe.com',
	    :card  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => 'Show & Tour Virtual Tour',
	    :currency    => 'usd'
	  )

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to dashboard_path
	end

	private

	def add_tour_credit
		current_user.tour_credits = current_user.tour_credits + 1
		current_user.save
	end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<div class="container">

	<div class="row">

		<h1 class="center">Thank you! Your tour is ready to use.</h1>

		<h1 class="center"><i class="fa fa-thumbs-o-up"></i></h1>

		<br><br>

		<div class="col-xs-4 col-xs-offset-4">
		  
		  <%= link_to new_tour_path, class: "btn btn-default dashboard-btn", :'data-no-turbolink' => "true" do %>
		    <i class="glyphicon-lg glyphicon glyphicon-plus-sign"></i>
		    <br /><br />
		    Create New Tour
		  <% end %>
		</div>

	</div>

	<br><br>

	<h4 class="center">Need help while creating your tour? Contact us a <a href="mailto:support@showandtour.com">support@showandtour.com</a></h4>

</div>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Virtual Tour"
          data-name="Show & Tour"
          data-amount="1200"></script>
<% end %>